### ISSUE TITLE
Error when trying to build

### ISSUE THREAD

**Issue by felipelalli** [rsksmart/utils#7]
NPM version 7.6.1

I get this error when trying to run `webpack`.

```
[webpack-cli] Error: Compiling RuleSet failed: Exclamation mark separated loader lists has been removed in favor of the 'use' property with arrays (at ruleSet[1].rules[1].loader: style!css)
    at RuleSetCompiler.error (/usr/local/lib/node_modules/webpack/lib/rules/RuleSetCompiler.js:373:10)
    at ruleSetCompiler.hooks.rule.tap (/usr/local/lib/node_modules/webpack/lib/rules/UseEffectRulePlugin.js:152:29)
    at Hook.eval [as call] (eval at create (/usr/local/lib/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:45:1)
    at RuleSetCompiler.compileRule (/usr/local/lib/node_modules/webpack/lib/rules/RuleSetCompiler.js:177:19)
    at rules.map (/usr/local/lib/node_modules/webpack/lib/rules/RuleSetCompiler.js:154:9)
    at Array.map (<anonymous>)
    at RuleSetCompiler.compileRules (/usr/local/lib/node_modules/webpack/lib/rules/RuleSetCompiler.js:153:16)
    at RuleSetCompiler.compileRule (/usr/local/lib/node_modules/webpack/lib/rules/RuleSetCompiler.js:184:30)
    at rules.map (/usr/local/lib/node_modules/webpack/lib/rules/RuleSetCompiler.js:154:9)
    at Array.map (<anonymous>)
    at RuleSetCompiler.compileRules (/usr/local/lib/node_modules/webpack/lib/rules/RuleSetCompiler.js:153:16)
    at RuleSetCompiler.compile (/usr/local/lib/node_modules/webpack/lib/rules/RuleSetCompiler.js:68:22)
    at new NormalModuleFactory (/usr/local/lib/node_modules/webpack/lib/NormalModuleFactory.js:235:34)
    at Compiler.createNormalModuleFactory (/usr/local/lib/node_modules/webpack/lib/Compiler.js:998:31)
    at Compiler.newCompilationParams (/usr/local/lib/node_modules/webpack/lib/Compiler.js:1018:30)
    at Compiler.compile (/usr/local/lib/node_modules/webpack/lib/Compiler.js:1029:23)
```

**Comment by julianmrodri** [comment]
Same issue. Seems to be broken. Any workaround we can use in the meantime?

**Comment by ndeet** [comment]
Same here, a bit concerning that this gets no love from maintainers tbh.

There is a fix in #4 it seems but #5 was merged which partly seems to fixed it but still does not work with webpack-cli >= 4.2. I got it working by installing older webpack-cli version 3.x (maybe need to uninstall previous version first): `npm install -g webpack-cli@3.3.12`

**Comment by franciscojs12** [comment]
Same thing, When running `webpack  `I get `Error: Cannot find module 'webpack-cli/package.json'`

**Comment by iemwill** [comment]
PR #9 should fix this, comment if not.

**Comment by franciscojs12** [comment]
> 

Yes, creating the build using `webpack` works with your branch,
